### ISSUE TITLE
90+层感知类型不正确

### ISSUE THREAD

**Issue by DreAmVirGo** [Etest2023/ff14-overlay-dungeon-cn#2]
晕不晕不太能了解。。。但是感知类型可以通过[https://docs.qq.com/doc/DSHNyVndhZkVqdHRo?groupUin=r4OcvbV8jU%252Ffs%252FCF8yjStQ%253D%253D](url)来纠正一下。

**Comment by DreAmVirGo** [comment]
> 晕不晕不太能了解。。。但是感知类型可以通过[https://docs.qq.com/doc/DSHNyVndhZkVqdHRo?groupUin=r4OcvbV8jU%252Ffs%252FCF8yjStQ%253D%253D](url)来纠正一下。

晕眩里面也有提，还是其他的一些加重啊啥的不太清楚）

**Comment by Etest2023** [comment]
外网的数据也是有一些不正确的。
这些数据主要靠实测，90层+能够实测的机会少，分享下你确定的哈

**Comment by Etest2023** [comment]
90+验了2次，没有问题。
根据文档补充了3个特殊怪的提示
