### ISSUE TITLE
非深层迷宫地图仍会显示击杀计数

### ISSUE THREAD

**Issue by Souma-Sumire** [Etest2023/ff14-overlay-dungeon-cn#4]
rt

**Comment by Etest2023** [comment]
这个技术上可以实现进迷宫才显示。
但是作为一个低频使用的悬浮窗，有内容提示用户注意开关悬浮窗，也是存在有必要的。
比如你的减伤悬浮窗齿轮、抹茶的物价悬浮窗展开收起

**Comment by Etest2023** [comment]
另外这个悬浮窗有个要求：在进迷宫前开启，才能在进本时收集到怪物信息

https://github.com/Etest2023/ff14-overlay-dungeon-cn/blob/0.2.0/src/modules/init.js

所以避免使用异常，还是要有内容展示
